"""Generate docs/cli-reference.md and book 12.2 from the click command tree, so the reference and `--help` never disagree (book 12, 13.4).

Usage: uv run python scripts/gen_cli_reference.py [--check]   (--check exits 1 when the checked-in file is stale)
"""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path

import click

from loom.cli import main
from loom.cli.help import SECTIONS

OUT = Path(__file__).resolve().parent.parent / "docs" / "cli-reference.md"
BOOK = Path(__file__).resolve().parents[2] / "docs" / "book" / "12-cli-reference.md"


def _normalise(text: str) -> str:
    """Docstrings keep or lose their indentation depending on the Python version; one space between words makes the output the same everywhere."""
    lines = [re.sub(r"[ \t]+", " ", ln).strip() for ln in inspect.cleandoc(text).splitlines()]
    return "\n".join(lines).strip()


def _usage_line(cmd: click.Command, path: list[str]) -> str:
    ctx = click.Context(cmd, info_name=" ".join(path))
    pieces = cmd.collect_usage_pieces(ctx)
    return " ".join([" ".join(path), *pieces]).strip()


def _runs_alone(cmd: click.Command) -> bool:
    """A group that is a command too (`loom history`): documented with its own usage and options, then its subcommands."""
    return isinstance(cmd, click.Group) and cmd.invoke_without_command


def _render(cmd: click.Command, path: list[str], depth: int, out: list[str]) -> None:
    name = " ".join(path)
    out.append(f"{'#' * min(depth, 4)} `{name}`")
    out.append("")
    if _runs_alone(cmd):
        # run alone it is a command with its own options; given a subcommand, the options before it are the group's
        alone = " ".join([name, *click.Command.collect_usage_pieces(cmd, click.Context(cmd, info_name=name))])
        out.append(f"`{alone.strip()}`")
        out.append("")
        out.append(f"`{_usage_line(cmd, path)}`")
        out.append("")
        out.append(f"Run alone, `{name}` is a command; its subcommands follow its options.")
        out.append("")
    else:
        out.append(f"`{_usage_line(cmd, path)}`")
        out.append("")
    if cmd.help:
        out.append(_normalise(cmd.help))
        out.append("")
    ctx = click.Context(cmd, info_name=name)
    # the help option is left out: its spelling depends on the context it was first rendered in, and every command has it
    params = [p for p in cmd.get_params(ctx) if isinstance(p, click.Option) and "--help" not in p.opts]
    if params:
        out.append("| option | description |")
        out.append("|---|---|")
        for p in params:
            opts = ", ".join(f"`{o}`" for o in [*p.opts, *p.secondary_opts])
            meta = f" `{p.metavar}`" if p.metavar else ""
            help_text = _normalise(p.help or "").replace("|", "\\|")
            out.append(f"| {opts}{meta} | {help_text} |")
        out.append("")
    if cmd is main:
        # the top level reads as `loom --help` does: the task sections in their order, each with its line of purpose
        listed = {n for _, _, names in SECTIONS for n in names}
        rest = sorted(n for n in cmd.commands if n not in listed)
        for title, purpose, names in [*SECTIONS, *([("Other", "", tuple(rest))] if rest else [])]:
            out.append(f"{'#' * min(depth + 1, 4)} {title}")
            out.append("")
            if purpose:
                out.append(purpose)
                out.append("")
            for sub_name in names:
                if sub_name in cmd.commands:
                    _render(cmd.commands[sub_name], [*path, sub_name], depth + 2, out)
    elif isinstance(cmd, click.Group):
        for sub_name in sorted(cmd.commands):
            sub = cmd.commands[sub_name]
            if sub.name != sub_name:
                continue  # an alias; the command is listed once under its own name
            _render(sub, [*path, sub_name], depth + 1, out)


def generate() -> str:
    out = [
        "# loom command reference",
        "",
        "Generated by `scripts/gen_cli_reference.py` from the command tree; do not edit. Every command has one name, listed in the sections of `loom --help`; a group that runs on its own is documented as a command, then with its subcommands.",
        "",
    ]
    _render(main, ["loom"], 1, out)
    return "\n".join(out).rstrip("\n") + "\n"


def spliced(book: str, generated: str) -> str:
    """Book 12 with section 12.2's reference replaced by `generated`, every heading one level down and the title dropped."""
    fence, lines = False, []
    for line in generated.split("\n")[2:]:
        fence ^= line.startswith("```")
        lines.append("#" + line if line.startswith("#") and not fence else line)
    start, end = book.index("Generated by `scripts/gen_cli_reference.py`"), book.index("## 12.9 ")
    return book[:start] + "\n".join(lines).rstrip("\n") + "\n\n" + book[end:]


if __name__ == "__main__":
    text = generate()
    book = BOOK.read_text(encoding="utf-8")
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text or book != spliced(book, text):
            print(f"{OUT} or book 12.2 is stale; run scripts/gen_cli_reference.py")
            sys.exit(1)
        print("cli-reference.md and book 12.2 are current")
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text, encoding="utf-8")
        BOOK.write_text(spliced(book, text), encoding="utf-8")
        print(f"wrote {OUT}")
